version: '3'

services:
  # Database layer
  database:
    image: mysql:8.0
    env_file:
      - ./.docker/mysql.env
    restart: always
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci'
    ]
    ports:
      - "13308:3306"
    volumes:
      - database:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  php:
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      args:
        ssh_prv_key: ./.docker/github
    env_file:
      - .docker/.env
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
    depends_on:
      - database

volumes:
  database:
